[package]
name = "async-epoll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "*"
waker-fn = { version = "1.1.0" }
smol = { version = "1.2.5" }